#!/bin/bash

# Script: Ops 201 Class 02 Ops Challenge Solution
# Author: Abel Ortega                      
# Date of latest revision:  7/26/2022    
# Purpose: Print a string to the terminal


# Main

# End
