#!/bin/bash

# Script: Ops 201 Class 02 Ops Challenge Solution
# Author: Abel Ortega                      
# Date of latest revision:  7/26/2022    
# Purpose: Print a string to the terminal


# Main
touch helloworld.sh
sudo nano helloworld.sh
#Here we enter whatever script such as // #!/bin/bash  echo "I am working perfectly"//
bash helloworld.sh
#Here we should now see "I am working perfectly"
# End
